name: Continuous Integration
on: push
env:
  DB_NAME: test
  DB_USER: root
  DB_PASSWORD: password
jobs:
  run_code_checks:
    runs-on: ubuntu-latest
    steps:
      - name: Setup MySQL
        run: |
          sudo /etc/init.d/mysql start
          sudo mysql -e 'alter user "${{env.DB_USER}}"@"localhost" identified by "${{env.DB_PASSWORD}}";' -uroot -proot
          sudo mysql -e 'create database ${{env.DB_NAME}};' -u${{env.DB_USER}} -p${{env.DB_PASSWORD}}
      - name: Checkout repo code
        uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21.1
      - name: Run linting
        run: |
          go fmt ./...
          go vet ./...
      - name: Run test
        run: go test